import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import { GlovalContextProvider } from "./Provider/GlovalContext";

import "aos/dist/aos.css";

const roboto = Roboto_Condensed({ subsets: ["latin"], weight: ["300", "400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <GlovalContextProvider>{children}</GlovalContextProvider>
      </body>
    </html>
  );
}
